CREATE EXTERNAL TABLE ejemplo.USUARIO(
  PERSONA STRING,
  EDAD INT,
  EDADRET INT,
  ANIONAC INT,
  MESNAC INT,
  SEXO STRING,
  DIRECCION STRING,
  APARTAMENTO  STRING,
  CIUDAD STRING,
  ESTADO STRING,
  ZIP STRING,
  LATITUD STRING,
  LONGITUD STRING,
  PERCAPITA STRING,
  INCOME STRING,
  TOTAL STRING,
  FICO STRING,
  NUMEROTARJETAS INT
  
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/grupo5Proy/Usuarios'
TBLPROPERTIES(
    'skip.header.line.count'='1',
    'store.charset'='ISO-8859-1', 
    'retrieve.charset'='ISO-8859-1'
);